# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

title: Disinfo
baseurl: ""
url: https://disinfo.quaidorsay.fr

exclude:
  - README.md
  - .circleci
  - vendor

kramdown:
  toc_levels: 2..4

plugins:
  - jekyll-redirect-from
